### ISSUE TITLE
Update Library 

### ISSUE THREAD

**Issue by JayceBryce** [calm/KenBurns#15]
Is this library ever going to be updated? @tsheaff

There also seems to be some pull request open that is updating to Swift 4.2.

Thank you

**Comment by tsheaff** [comment]
Hey @JayceBryce thanks for asking. This library isn't currently being actively developed by Calm, but it's a really great foundation that you can fork and build off of at your leisure.

**Comment by JayceBryce** [comment]
@tsheaff Thanks for the reply! How am I suppose to update the dependencies this cocoapod uses? For example SDWebImage is currently at version 5.0.2 but this library is at 3.8.2.
