### ISSUE TITLE
SDWebImage compiler warning

### ISSUE THREAD

**Issue by nannestad** [calm/KenBurns#9]
KenBurns.swift is giving me a compiler warning on line 165 because of the call to the deprecated SDWebView function `setImageWith:placeholder:`.

Instead use the `sd_setImageWithURL:placeholderImage:` function.

**Comment by tsheaff** [comment]
OK, submit a PR and I'll accept it.  Which version of `SDWebImage` are you using? The `KenBurns` podspec specifies `~> 3.8.1`, but the latest is 4.0.0

**Comment by nannestad** [comment]
For some reason the SDWebImage Info.plist says version 3.8.2 but I can see that KenBurns specifies 3.8.1. I've just recently taken over this project so I don't really know why this is but I guess updating KenBurns to use the new SDWebImage api will fix the issue.

**Comment by tsheaff** [comment]
Yeah @nannestad better to move forward than to stay on the earlier version. As for 3.8.2, I think it's because it's specified as `~> 3.8.1` which will be anything >= 3.8.1 and < 4.0.0 (locks to major version = 3 and minor+patch >= 8.1, which 3.8.2 falls under).

**Comment by nannestad** [comment]
I can't see that the pod is updated with these changes: [https://cocoapods.org/?q=kenburn](url) Am I doing something wrong?

**Comment by tsheaff** [comment]
Yeah you're right. The ruby symbol prefix `:` was making the validation fail.  After this commit https://github.com/calm/KenBurns/commit/fe35a84657295a3128a713b2a45a163048409060 it worked and is now live:

```
Tylers-MacBook-Pro-2:KenBurns tsheaff$ pod spec lint

 -> KenBurns (0.2.8)

Analyzed 1 podspec.

KenBurns.podspec passed validation.

Tylers-MacBook-Pro-2:KenBurns tsheaff$ pod trunk push

[!] Found podspec `KenBurns.podspec`
Updating spec repo `master`
Validating podspec
 -> KenBurns (0.2.8)

Updating spec repo `master`

--------------------------------------------------------------------------------
 🎉  Congrats

 🚀  KenBurns (0.2.8) successfully published
 📅  May 9th, 09:48
 🌎  https://cocoapods.org/pods/KenBurns
 👍  Tell your friends!
--------------------------------------------------------------------------------
```
